server:
  port: 8080

---
spring:
  profiles: default
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

api:
  url:
    product: http://localhost:8085
    delivery: http://localhost:8082

server:
  port: 8081
---
spring:
  profiles: docker
#  sleuth:
#    sampler:
#      probability: 1
#    web:
#      skipPattern: (^cleanup.*|.+favicon.*)

api:
  url:
    product: http://products:8080
    delivery: http://delivery:8080
