apiVersion: apps/v1
kind: Deployment
metadata:
  name: BoundedContext57.499961853027344
  labels:
    app: BoundedContext57.499961853027344
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BoundedContext57.499961853027344
  template:
    metadata:
      labels:
        app: BoundedContext57.499961853027344
    spec:
      containers:
        - name: BoundedContext57.499961853027344
          image: username/BoundedContext57.499961853027344:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5