apiVersion: apps/v1
kind: Deployment
metadata:
  name: BoundedContext115
  labels:
    app: BoundedContext115
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BoundedContext115
  template:
    metadata:
      labels:
        app: BoundedContext115
    spec:
      containers:
        - name: BoundedContext115
          image: username/BoundedContext115:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5